### ISSUE TITLE
Find item with multiple ISBNs returns incorrect results

### ISSUE THREAD

**Issue by Baroquem** [jrochkind/borrow_direct#1]
I’ve come across a bug in the borrow_direct gem when trying to do a find with multiple ISBNs for the same item. It took me a while to pin it down, but I finally realized what’s going on.

Currently, doing something like this:

```
isbns = [‘9780821419755’, ‘0821419757’]
BorrowDirect::FindItem.new.find(:isbn => isbns)
```

produces a hash that looks like this:

```
{
  "PartnershipId"=>"BD", 
  "ExactSearch"=>[
    {"Type"=>"ISBN", "Value"=>”9780821419755"}, 
    {"Type"=>"ISBN", "Value"=>”0821419757"}
  ]
}
```
However, this call yields incorrect results. A search of either ISBN individually shows that the item is available in BD, but trying the above search with two ISBNs returns a response of “unavailable”. This is because the hash — or rather, the JSON it’s converted into in request.rb — is improperly formed. According to Relais, the correct format should be:

```
{
  "PartnershipId": "BD",
  "ExactSearch": [{"Type": "ISBN", "Value": "9780821419755"}],
  "ExactSearch": [{"Type": "ISBN", "Value": "0821419757"}]
}

```
So a hash won’t work here because duplicate keys are needed. I tried to find a gentle way of modifying the code in find_item.rb to handle this, but I haven’t come up with anything yet. 

Also, on a very minor note, TEST_API_BASE should be updated to https://bdtest.relais-host.com/ (rc.relais-host is no longer working properly).

**Comment by jrochkind** [comment]
Thanks for your report!

I suspect it's a bug/limitation in the BD API itself. I was _very_ limited by the underlying BD API in writing this -- the BD API is under-documented, and frequently performs in unexpected ways, and I never really had a succesful dialog with the vendor about most of it, just had to take it as it was. 

I'd recommend going down the direct BD API access level to figure out what's going on. If there's a way to change the gem source code to do better, we can -- but I think it's far more likely it's a limitation or bug in the BD API itself, and you'll just have to report it to the vendor. 

I don't actually currently work at an institution with BorrowDirect access, so it's difficult for me to troubleshoot or develop this (not to mention no longer part of my job!).   But I'm happy to review any pull requests -- want to send a pull request to update TEST_API_BASE?    Once you (or anyone) subits a significant pull request succesfully, I'd be happy to such programmers committers as well.

**Comment by jrochkind** [comment]
Ah, sorry, I didn't read carefully enough -- I see you say you've figured it out and the request was malformed, and does work correctly when formed differently?

I was operating off the very limited docs that existed and similar very limited information I was able to get from Relais beyond the docs. 

But if you are sure you've fixed it, please submit a pull request and I'm happy to merge it!  It should come with a test if it's at all feasible.

**Comment by jrochkind** [comment]
(I was never able to get multi-ISBN search to work either! But was never able to get an answer or response from Relais myself! So good job on that!)

**Comment by Baroquem** [comment]
Yes, I'm pretty confident at this point that the problem is in the gem and not the API. I was a bit leery of trying to make the fix myself, since it affects the central "request" function and I'm not sure what all the consequences of altering that would be. But I'll dig into it a bit more and see if I can come up with something. Thanks!

**Comment by jrochkind** [comment]
Cool. I can take a quick look too, shouldn't be hard to fix, I'll try to take a look this week -- but since I don't have access to the BD API myself now, what would really help is if you could contribute a failing test, then later verify if my code makes it pass.

**Comment by jrochkind** [comment]
(And/or share BD credentials with me in private email, so I can actually run tests)

**Comment by jrochkind** [comment]
Ugh, this is a pain. Why the heck did they make the value of ExactSearch an _array_ if it always has to only have one item?

It is difficult to generate a JSON hash with multiple repeated keys -- it doesn't really make sense as JSON, so standard JSON generating tools don't deal well with it. 

This is a terribly designed API. The fact that the value needs to be an array suggests someone originally meant to design it like I implemented for, but then someone at Relais implemented it in a totally ridiculous way. 

Still not sure the best way to handle, really have to fight with JSON generating tools to do with BD wants, might have to generate the JSON-like hash at least partially manually. 

More on duplicate keys in JSON can be found on [this SO](http://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object) -- it's unclear if it's legal JSON, some standards say no, some standards leave it unsaid; but most JSON handling libraries aren't prepared for it.

**Comment by jrochkind** [comment]
Also please note that BD's own documentation matches what this gem originally implemented, and not what BD support staff has told you. See: https://relais.atlassian.net/wiki/display/ILL/Find+Item?preview=/32112647/58753026/Find%20Item%20-%20multiple%20ISBNs

Specifically, note from the above example:

~~~
{  "PartnershipId": "BD",  
   "ExactSearch":[
      {   "Type": "ISBN",
          "Value": "9780821419755"      },
      {   "Type": "ISBN",
          "Value": "0821419757"      },
      {   "Type": "ISBN",
          "Value": "9780821420393"      },
      {   "Type": "ISBN",          
         "Value": "0821420399"      }  ]}
~~~

I'd get Peter to get get Relais to fix the service to match the documentation as above. This code was written to that documentation.  They can't just go changing what they say the API is all the time -- without even updating the docs!  Super frustrating!  Plus this change is totally a pain to implement. They need to fix it to match what is documented. 

It's certainly possible to get the code to use their undocumented totally ridiculous way of doing things, if they won't, but I'm not sure i'm going to have the time to do it. I'd at least talk to Peter about the situation and point out the docs I link above, documenting something different than you have been told.

**Comment by Baroquem** [comment]
Jonathan — I quite agree with what you've said. And in fact, after banging my head against this problem for a few days, I came to the same conclusions and contacted Peter about the possibility of having Relais fix things. Relais have now responded (at least they're responding!) and told us that they had, in fact, given me erroneous information before. The format that you quoted above — and that the gem implements — is the correct one after all.

I'm very sorry for my part in sending us both on a wild goose chase, and I hope you haven't dedicated too much time to this issue. There's still *something* that's occasionally giving me strange results from the API, but it looks like the gem isn't the source of the trouble. I hadn't had time to go back yet and confirm that the revised format they sent me is the same as the one you coded, but I think you've done that now in your comments. I'll go ahead and close this issue. Again, sorry for the trouble.

**Comment by jrochkind** [comment]
Okay, cool. 

No apologies needed from you -- I've dealt with Relais too, getting accurate information out of them about the API is _very hard_. 

I went and found the docs from Relais with the example that is what the current gem code is requesting, so that would probably be good to point out to them next time they try to claim it's different.
